version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            docker pull ubcrocket/majortombuild
            ./dmake.sh
      - run:
          name: Run sharetest image
          command: |
            cd build
            ./mock sharetest
