version: 2
jobs:
  build:
    docker:
      - image: ubcrocket/majortombuild
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build project
          command: |
            cd build
            make clean
            make
      - run:
          name: Run sharetest image
          command: |
            cd build
            python ../test-can/genreate_test_file.py
            ./mock sharetest
