version: 2
jobs:
  build:
    docker:
      - image: ubcrocket/majortombuild
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            cd build
            make
            ls
