version: 2
jobs:
  build:
    docker:
      - image: ubcrocket/majortombuild
    machine: true
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            ./dmake.sh
      - run:
          name: Run sharetest image
          command: |
            cd build
            ./mock sharetest
